version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: example_user
      DB_PASSWORD: example_password
      DB_NAME: test

  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: test
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: