version: '3.8'

services:
  frontend:
    image: jainam05/healthnest:frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    image: jainam05/healthnest:backend
    ports:
      - "8085:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: example_user
      DB_PASSWORD: example_password
      DB_DATABASE: test

  mysql:
    image: jainam05/healthnest:mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mysql-data: